"""update db 1.1

Revision ID: 2c1b58f5c554
Revises: b678407c9dbb
Create Date: 2024-01-21 16:12:13.251798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1b58f5c554'
down_revision = 'b678407c9dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bph_coconut',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_lengkap', sa.String(length=40), nullable=True),
    sa.Column('nra', sa.String(length=9), nullable=True),
    sa.Column('wa', sa.String(length=20), nullable=True),
    sa.Column('jurusan', sa.String(length=15), nullable=True),
    sa.Column('profile', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nra'),
    sa.UniqueConstraint('wa')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_email', ['email'])
        batch_op.create_unique_constraint('unique_nomor_wa', ['nomor_wa'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_nomor_wa', type_='unique')
        batch_op.drop_constraint('unique_email', type_='unique')

    op.drop_table('bph_coconut')
    # ### end Alembic commands ###
