"""update db 1.2

Revision ID: 5be9069490ff
Revises: 2c1b58f5c554
Create Date: 2024-01-21 16:40:19.623648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be9069490ff'
down_revision = '2c1b58f5c554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bph_coconut', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kampus', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bph_coconut', schema=None) as batch_op:
        batch_op.drop_column('kampus')

    # ### end Alembic commands ###
