"""update db 1.3

Revision ID: 7fa5d01388d8
Revises: 5be9069490ff
Create Date: 2024-01-21 18:57:47.465034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa5d01388d8'
down_revision = '5be9069490ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bph_coconut', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depart', sa.String(length=22), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bph_coconut', schema=None) as batch_op:
        batch_op.drop_column('depart')

    # ### end Alembic commands ###
