"""update db 1.0

Revision ID: b678407c9dbb
Revises: 
Create Date: 2024-01-18 23:36:17.117014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b678407c9dbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode', sa.String(length=10), nullable=True),
    sa.Column('pemilik', sa.String(length=50), nullable=True),
    sa.Column('keterangan', sa.String(length=240), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_lengkap', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('nomor_wa', sa.String(length=20), nullable=True),
    sa.Column('asal_kampus', sa.String(length=64), nullable=True),
    sa.Column('bukti_tf', sa.String(length=64), nullable=True),
    sa.Column('bukti_follow', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='unique_email'),
    sa.UniqueConstraint('nomor_wa'),
    sa.UniqueConstraint('nomor_wa', name='unique_nomor_wa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('certificate')
    # ### end Alembic commands ###
